---

- name: Install unzip package
  apt: name=unzip state=present

- name: Check if Wordpress has been presviosly Downloaded
  stat: path="{{ wp_download_path }}"
  register: wp_zipped

- name: Download Wordpress
  get_url: url="{{ wp_url }}" dest="{{ wp_download_path }}"
  when: wp_zipped.stat.exists == False

- name: Unzip Wordpress
  unarchive: src="{{ wp_download_path }}" dest="{{ wp_webserver_path }}" copy=no

- name: Copy Wp-config.php
  template: src=wp-config.php.j2 dest="{{ wp_webserver_path }}/wordpress/wp-config.php"
